#include "crypto.h"

void generate_transaction_id(uint8_t tid[12]) {
    time_t now = time(NULL);
    uint64_t ts = (uint64_t)now;

    /*
    * The 24 bits within the ts are shifted to the right, and then & 0xFF is applied to retain only the lowest 8 bits.
    * This extracts a specific byte from the number.
    *
    * 0xff = binary 11111111, so only uses for select 8 byte. 
    */
    tid[0] = (ts >> 24) & 0xFF;
    tid[1] = (ts >> 16) & 0xff;
    tid[2] = (ts >> 8)  & 0xFF;
    tid[3] = ts & 0xFF;

    // the ID of this program process in the operating system
    uint16_t pid = (uint16_t)getpid();

    // we write the high and low bytes of the PID separately
    tid[4] = (pid >> 8) & 0xff;
    tid[5] = pid & 0xff;

    // the last 6 bytes consist of the lower 8 bits generated by rand()
    for (int i = 6; i < 12; i++)
        tid[i] = (uint8_t)(rand() & 0xFF);
}
