#include <asm-generic/socket.h>
#include <stddef.h>
#define _GNU_SOURCE

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <stdint.h>
#include <time.h>
#include <errno.h>
#include <signal.h>
#include <fcntl.h>

#include <poll.h>
#include <arpa/inet.h>
#include <sys/socket.h>
#include <sys/time.h>
#include <netinet/in.h>
#include <netdb.h>

/*
* In some libc/compilation combinations, this macro
* may be required to declare endian functions
*/
#ifndef __USE_MISC
#define __USE_MISC
#endif

/*
* htobe64: Converts a 64-bit number in host byte order to big-endian byte order.
* be64toh: Converts a 64-bit number in big-endian format to the machine's native byte order.
*/
#include <endian.h>

#define DEFAULT_STUN_HOST "stun.l.google.com"
#define DEFAULT_STUN_PORT 19302
#define STUN_TIMEOUT_SEC  5
#define STUN_MAX_ATTEMPTS 3

#define MAX_BUFFER_SIZE   1500
#define PUNCH_INTERVAL_MS 300
#define PING_INTERVAL_MS  1000
#define PING_TIMEOUT_MS   2000

/* The maximum time to wait for a single poll() call. */
#define POLL_SLICE_MS     100

/* STUN HEADER (RFC 5389)
* STUN header total size is 20 byte:
* 0..1  : Message Type   (2 byte)
* 2..3  : Message Length (2 byte)
* 4..7  : Magic Cookie   (4 byte)
* 8..19 : Transaction ID (12 byte)
*
* __attribute__((packed)): Prevents the compiler from adding extra bytes
* for alignment between struct fields.
*/
typedef struct __attribute__((packed)) {
    uint16_t msg_type;
    uint16_t msg_length;         // payload length after header
    uint32_t magic_cookie;       // RFC 5389 constant: 0x2112A442
    uint8_t  transaction_id[12]; // Request-response pairing ID
} stun_header_t;

/*
* Converts the STUN header structure into a raw byte sequence to be sent
* over the network.
* 
* Why isn't `memcpy(&header, ...)` used directly?:
* This is because the CPU's native byte order may be little-endian. On the network,
* however, multi-byte numbers must be transmitted in big-endian/network byte order.
*/
static int stun_header_to_binary(const stun_header_t *header, uint8_t *buffer, size_t buf_len) {
    // min 20 byte acceptible
    if (buf_len < sizeof(stun_header_t))
        return -1;

    // host to network short
    uint16_t mt = htons(header->msg_type), ml = htons(header->msg_length);

    // host to network long
    uint32_t mc = htonl(header->magic_cookie);

    // write the header fields to the correct byte offsets specified in the RFC
    memcpy(buffer,     &mt, 2); /* 0..1 type */
    memcpy(buffer + 2, &ml, 2); /* 2..3: length */
    memcpy(buffer + 4, &mc, 4); /* 4..7: cookie */
    memcpy(buffer + 8, header->transaction_id, 12); /* 8..19: TID */
    
    return (int)sizeof(stun_header_t);
}

/*
* Parses the header of the raw STUN data retrieved from the network.
*/
static int stun_header_from_binary(const uint8_t *buffer, size_t buf_len, stun_header_t *header) {
    if (buf_len < sizeof(stun_header_t))
        return -1;

    // converts from network byte order to host byte order
    header->msg_type = ntohs(*(const uint16_t *)(buffer + 0));
    header->msg_length = ntohs(*(const uint16_t *)(buffer + 2));
    header->magic_cookie = ntohl(*(const uint32_t *)(buffer + 4));

    // since the transaction ID is a byte array, no byte order conversion is required
    memcpy(header->transaction_id, buffer + 8, 12);

    if (header->magic_cookie != 0x2112A442)
        return -1;

    return 0;
}

/*
* It generates a 12-byte transaction ID for the STUN request.
*/
static void generate_transaction_id(uint8_t tid[12]) {
    time_t now = time(NULL);
    uint64_t ts = (uint64_t)now;

    /*
    * The 24 bits within the ts are shifted to the right, and then & 0xFF is applied to retain only the lowest 8 bits.
    * This extracts a specific byte from the number.
    *
    * 0xff = binary 11111111, so only uses for select 8 byte. 
    */
    tid[0] = (ts >> 24) & 0xFF;
    tid[1] = (ts >> 16) & 0xff;
    tid[2] = (ts >> 8)  & 0xFF;
    tid[3] = ts & 0xFF;

    // the ID of this program process in the operating system
    uint16_t pid = (uint16_t)getpid();

    // we write the high and low bytes of the PID separately
    tid[4] = (pid >> 8) & 0xff;
    tid[5] = pid & 0xff;

    // the last 6 bytes consist of the lower 8 bits generated by rand()
    for (int i = 6; i < 12; i++)
        tid[i] = (uint8_t)(rand() & 0xFF);
}

/*
* It extracts the public IP address and port from
* the XOR-MAPPED-ADDRESS attribute in the STUN response.
* 
* What is XOR-MAPPED-ADDRESS?: The STUN server returns the external
* IP:port address it sees for the client. This information is sent
* in an XOR-encrypted format rather than in plain text.
*
* Why is XOR using?: To reduce the likelihood that legacy NAT ALG
* devices will inadvertently alter the IP/port information visible in the packet.
*
* XOR OPERATION:
* XOR = exclusive OR
*
* The operation A ^ B returns the initial value when the same B value
* is applied again:
* (A ^ B) ^ B = A
*
* That's why we can restore the port/IP value that the STUN server XORed by performing
* an XOR operation with the same constant.
*
* Params:
* - buffer: STUN payload start
* - payload_len: Payload length after the header
* - mapped_ip_be: Response public IP (in network byte order form)
* - mapped_port_host: Response public PORT (in host byte order form)
*/
static int parse_xor_mapped_address(const uint8_t *buffer, size_t payload_len, uint32_t *mapped_ip_be, uint16_t *mapped_port_host) {
    if (payload_len < 12)
        return -1;

    // first 2 byte STUN attribute type field
    uint16_t attr_type = ntohs(*(const uint16_t *)(buffer + 0));

    // 0x0020 = XOR-MAPPED-ADDRESS attribute type
    if (attr_type != 0x0020)
        return -1;

    /* attribute header is 4 byte
    * - 2 byte type
    * - 2 byte length
    * value field starts at buffer + 4
    */
    const uint8_t *value = buffer + 4;

    /*
    * value[0]: reserved, ussally 0
    * value[1]: address family
    * 
    * 0x01 = IPv4
    * 0x02 = IPv6
    */
    uint8_t family = *(value + 1);
    if (family != 0x01)
        return -1;

    /*
    * There is a 16-bit port XORed with value + 2.
    * The port has been XORed with 0x2112, which is the upper 16
    * bits of the magic cookie.
    */
    uint16_t xor_port = *(const uint16_t *)(value + 2);
    uint16_t port_host = ntohs(xor_port) ^ 0x2112;
    
    /*
    * There is a IPv4 address XORed with value + 4.
    * IPv4 address, XORed with 32-byte magic cookie.
    */
    uint32_t xor_ip_host = ntohl(*(const uint32_t *)(value + 4));
    uint32_t ip_host = xor_ip_host ^ 0x2112A442;

    // now port is ready in host byte order form
    *mapped_port_host = port_host;
    /*
    * Network functions such as `sockaddr_in` and `inet_ntoa` expect
    * the IP address to be in network byte order. Therefore, `htonl`
    * is applied again.
    */
    *mapped_ip_be = htonl(ip_host);

    return 0;
}

/*
* Resolve a hostname to IPv4
*/
static int resolve_hostname(const char *hostname, struct sockaddr_in *addr) {
    /* I WON'T WRITE ANY EXPLANATION FOR THIS SECTION, BECAUSE THIS SECTION IS REALLY
    MUCH EASIER THAN THE OTHER SECTIONS */ 
    struct addrinfo hints = {0}, *result, *rp;
    hints.ai_family = AF_INET;
    hints.ai_socktype = SOCK_DGRAM;
    int ret;
    if ((ret = getaddrinfo(hostname, NULL, &hints, &result)) != 0) {
        fprintf(stderr, "[ERR] getaddrinfo: %s\n", gai_strerror(ret));
        return -1;
    }
    for (rp = result; rp != NULL; rp = rp->ai_next) {
        if (rp->ai_family == AF_INET) {
            memcpy(addr, rp->ai_addr, sizeof(*addr));
            freeaddrinfo(result);
            return 0;
        }
    }
    freeaddrinfo(result);
    return -1;
}

/*
* It sends a STUN Binding Request over the open UDP socket and
* returns the public IP:port value as seen by the STUN server.
*
* This function does not open a separate socket; it uses the
* socket (sock_fd) opened by main(). The reason for this is
* that a NAT device typically establishes mappings based on
* the local IP address and port and the destination. It is important
* that the socket used in the STUN query be the same as the one used
* in P2P hole punching in order to preserve the external port mapping.
*
* Params:
* - sock_fd : binded socket file descriptor
* - stun_host : IP or Hostname
* - stun_port : STUN UDP port
* - out_ip : the buffer where the public IPv4 text will be written
* - out_ip_len : out_ip capacity
* - out_port : where to enter the public UDP port
*/
static int stun_discover(int sock_fd, const char *stun_host, uint16_t stun_port, char *out_ip, size_t out_ip_len, uint16_t *out_port) {
    // STUN server network address
    struct sockaddr_in stun_addr = {0};
    stun_addr.sin_family = AF_INET;

    if (inet_pton(AF_INET, stun_host, &stun_addr.sin_family) <= 0) {
        if (resolve_hostname(stun_host, &stun_addr) < 0) {
            fprintf(stderr, "[ERR] STUN server not resolved: %s\n", stun_host);
            return -1;
        }
    }
    stun_addr.sin_port = htons(stun_port);

    // 5 sec. sock-level timeout for recvfrom()
    struct timeval tv = {
        .tv_sec = STUN_TIMEOUT_SEC,
        .tv_usec = 0
    };

    setsockopt(sock_fd, SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof(tv));
    
    for (int attempt = 1; attempt <= STUN_MAX_ATTEMPTS; attempt++) {
        // that's will starts Request Header with zero 
        stun_header_t req = {0};

        /*
        * 0x0001 = Binding request.
        * It is a question asked of the STUN server: “From which IP:port are
        * you seeing me?”
        */
        req.msg_type = 0x0001;
        // No additional payload/attribute after header in this request
        req.msg_length = 0;
        // RFC 5389 magic cookie
        req.magic_cookie = 0x2112A442;
        generate_transaction_id(req.transaction_id);
        uint8_t req_buf[20];
        int req_len = stun_header_to_binary(&req, req_buf, sizeof(req_buf));

        if (sendto(sock_fd, req_buf, req_len, 0, (struct sockaddr *)&stun_addr, sizeof(stun_addr)) < 0) {
            fprintf(stderr, "[ERR] STUN sendto (test %d/%d): %s\n", attempt, STUN_MAX_ATTEMPTS, strerror(errno));
            continue;
        }

        // general UDP buffer to receive the STUN response
        uint8_t resp_buf[MAX_BUFFER_SIZE];
        // the return address is entered here
        struct sockaddr_in from_addr;
        socklen_t from_len = sizeof(from_addr);

        ssize_t n = recvfrom(sock_fd, resp_buf, sizeof(resp_buf), 0, (struct sockaddr *)&from_addr, &from_len);
        if (n < 0) {
            fprintf(stderr, "[WAR] Can't received STUN response (test %d/%d): %s\n", attempt, STUN_MAX_ATTEMPTS, strerror(errno));
            continue;
        }

        // parse the STUN header of the incoming packet
        stun_header_t resp;
        
        if (stun_header_from_binary(resp_buf, (size_t)n, &resp) < 0)
            continue;

        // 0x0101 = Binding Success Response
        if (req.msg_type != 0x0101)
            continue;

        // make sure the response is for the request we just sent
        if (memcmp(req.transaction_id, resp.transaction_id, 12) != 0)
            continue;

        // STUN payload: data of after the header
        const uint8_t *payload = resp_buf + sizeof(stun_header_t);
        // to ensure security, the header size is subtracted from the total number of bytes
        size_t payload_len = (size_t)n - sizeof(stun_header_t);

        // parsed public IP & port
        uint32_t ip_be;
        uint16_t port_host;

        if (parse_xor_mapped_address(payload, payload_len, &ip_be, &port_host) < 0)
            continue;

        // put binary IPv4 address in to struct in_addr
        struct in_addr ia = {
            .s_addr = ip_be
        };

        strncpy(out_ip, inet_ntoa(ia), out_ip_len - 1);

        out_ip[out_ip_len - 1] = '\0';
        *out_port = port_host;

        return 0;
    }

    fprintf(stderr, "[ERR] STUN discovery %d, test is failed.\n", STUN_MAX_ATTEMPTS);
    return -1;
}
